version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_DB=orcamento
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - type: tmpfs
        target: /dev/shm
      - ./scripts/criar_banco.sql:/docker-entrypoint-initdb.d/criar_banco.sql
      - ./scripts/povoar_banco.sql:/docker-entrypoint-initdb.d/povoar_banco.sql
volumes:
  pgdata: