version: '3.8'

services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_DB=cggov_orc
      - POSTGRES_USER=cggov
      - POSTGRES_PASSWORD=sinfracggov
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./scripts/criar_banco.sql:/docker-entrypoint-initdb.d/criar_banco.sql
      - ./scripts/povoar_banco.sql:/docker-entrypoint-initdb.d/povoar_banco.sql
volumes:
  pgdata: